sudo: required
branches:
  only:
    - dev
language:
    - cpp
compiler:
    - gcc
jobs:
  include:
    - stage: cmake
      script:
      - cmake .
      - make
      - ./CMake-test
      - ctest
    - stage: ctest
      script:
      - ctest
notifications:
   #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
