sudo: required
branches:
  only:
    - master
language:
    - cpp

compiler:
    - gcc

script:
    - cmake .
    - make
    - ctest
    - cmake -H. -Bbuild
    - cmake --build build -- -j3
    - ./build/test
notifications:
   #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
