sudo: required
branches:
  only:
    - dev
language:
    - cpp
# os:
#   - linux
#   - osx
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2
compiler:
    - gcc
    - clang
# jobs:
#   include:
    # - stage: cmake
    #   script:
    #   - cmake .
    #   - make
    #   - ./CMake-test
    #   - ctest
    # - stage: ctest
    #   script:
    #   - ctest
    # - stage: Second method
# before_script:
# To upgrade to 3.13.3
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake ; fi
script:
- mkdir _builds
- cd _builds
- cmake ..
- make
- ctest
- cmake --version
notifications:
   #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
